webapp/src/Entity/Team.php
<?php declare(strict_types=1);

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use JMS\Serializer\Annotation as Serializer;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Context\ExecutionContextInterface;

/**
 * All teams participating in the contest
 * @ORM\Entity()
 * @ORM\Table(
 *     name="team",
 *     options={"collate"="utf8mb4_unicode_ci", "charset"="utf8mb4"},
 *     indexes={
 *         @ORM\Index(name="affilid", columns={"affilid"}),
 *         @ORM\Index(name="categoryid", columns={"categoryid"})
 *     },
 *     uniqueConstraints={
 *         @ORM\UniqueConstraint(name="icpcid", columns={"icpcid"}, options={"lengths": {"190"}}),
 *     })
 * @UniqueEntity("icpcid")
 */
class Team extends BaseApiEntity implements ExternalRelationshipEntityInterface
{
    /**
     * @var int
     *
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * @ORM\Column(type="integer", name="teamid", length=4, options={"comment"="Team ID", "unsigned"=true}, nullable=false)
     * @Serializer\SerializedName("id")
     * @Serializer\Type("string")
     */
    protected $teamid;

    /**
     * @var string
     * @ORM\Column(type="string", name="icpcid", length=255, options={"comment"="Team ID in the ICPC system",
     *                            "collation"="utf8mb4_bin","default"="NULL"}, nullable=true)
     * @Serializer\SerializedName("icpc_id")
     */
    protected $icpcid;

    /**
     * @var string
     * @ORM\Column(type="string", name="name", length=255, options={"comment"="Team name", "collation"="utf8mb4_bin"},
     *                            nullable=false)
     */
    private $name;

    /**
     * @var string|null
     * @ORM\Column(type="string", name="display_name", length=255, options={"comment"="Team display name", "collation"="utf8mb4_bin"},
     *                            nullable=true)
     */
    private $display_name;

    /**
     * @var int
     * @ORM\Column(type="integer", name="categoryid", options={"comment"="Team category ID","unsigned"="true","default"=0}, nullable=false)
     * @Serializer\Exclude()
     */
    private $categoryid = 0;

    /**
     * @var int
     * @ORM\Column(type="integer", name="affilid", options={"comment"="Team affiliation ID","unsigned"="true","default"="NULL"}, nullable=true)
     * @Serializer\SerializedName("organization_id")
     * @Serializer\Type("string")
     */
    private $affilid;

    /**
     * @var boolean
     * @ORM\Column(type="boolean", name="enabled",
     *     options={"comment"="Whether the team is visible and operational",
     *              "default"=1},
     *     nullable=false)
     * @Serializer\Exclude()
     */
    private $enabled = true;

    /**
     * @var string
     * @ORM\Column(type="text", length=4294967295, name="members", options={"comment"="Team member names (freeform)","default"="NULL"},
     *                          nullable=true)
     * @Serializer\Groups({"Nonstrict"})
     */
    private $members;

    /**
     * @var string
     * @ORM\Column(type="string", length=255, name="room", options={"comment"="Physical location of team","default"="NULL"},
     *                            nullable=true)
     * @Serializer\Exclude()
     */
    private $room;

    /**
     * @var string
     * @ORM\Column(type="text", length=4294967295, name="comments", options={"comment"="Comments about this team","default"="NULL"},
     *                          nullable=true)
     * @Serializer\Exclude()
     */
    private $comments;

    /**
     * @var double
     * @ORM\Column(type="decimal", precision=32, scale=9, name="judging_last_started",
     *     options={"comment"="Start time of last judging for priorization",
     *              "unsigned"=true,"default"="NULL"}, nullable=true)
     * @Serializer\Exclude()
     */
    private $judging_last_started;

    /**
     * @var int
     * @ORM\Column(type="integer", name="penalty",
     *     options={"comment"="Additional penalty time in minutes","default"=0},
     *     nullable=false)
     * @Serializer\Exclude()
     */
    private $penalty = 0;

    /**
     * @var bool
     * @Serializer\Exclude()
     */
    private $addUserForTeam = false;

    /**
     * @ORM\ManyToOne(targetEntity="TeamAffiliation", inversedBy="teams")
     * @ORM\JoinColumn(name="affilid", referencedColumnName="affilid", onDelete="SET NULL")
     * @Serializer\Exclude()
     */
    private $affiliation;

    /**
     * @ORM\ManyToOne(targetEntity="TeamCategory", inversedBy="teams")
     * @ORM\JoinColumn(name="categoryid", referencedColumnName="categoryid", onDelete="CASCADE")
     * @Serializer\Exclude()
     */
    private $category;

    /**
     * @ORM\ManyToMany(targetEntity="Contest", mappedBy="teams")
     * @Serializer\Exclude()
     */
    private $contests;

    /**
     * @ORM\OneToMany(targetEntity="User", mappedBy="team")
     * @Serializer\Exclude()
     * @Assert\Valid()
     */
    private $users;

    /**
     * @ORM\OneToMany(targetEntity="Submission", mappedBy="team")
     * @Serializer\Exclude()
     */
    private $submissions;

    /**
     * @ORM\OneToMany(targetEntity="Clarification", mappedBy="sender")
     * @Serializer\Exclude()
     */
    private $sent_clarifications;

    /**
     * @ORM\OneToMany(targetEntity="Clarification", mappedBy="recipient")
     * @Serializer\Exclude()
     */
    private $received_clarifications;

    /**
     * @ORM\ManyToMany(targetEntity="Clarification")
     * @ORM\JoinTable(name="team_unread",
     *                joinColumns={@ORM\JoinColumn(name="teamid", referencedColumnName="teamid", onDelete="CASCADE")},
     *                inverseJoinColumns={@ORM\JoinColumn(name="mesgid", referencedColumnName="clarid", onDelete="CASCADE")}
     * )
     * @Serializer\Exclude()
     */
    private $unread_clarifications;

    /**
     * Set teamid
     *
     * @param int $teamid
     *
     * @return Team
     */
    public function setTeamid($teamid)
    {
        $this->teamid = $teamid;

        return $this;
    }

    /**
     * Get teamid
     *
     * @return integer
     */
    public function getTeamid()
    {
        return $this->teamid;
    }

    /**
     * Set icpcid
     *
     * @param string $icpcid
     *
     * @return Team
     */
    public function setIcpcid($icpcid)
    {
        $this->icpcid = $icpcid;

        return $this;
    }

    /**
     * Get icpcid
     *
     * @return string
     */
    public function getIcpcid()
    {
        return $this->icpcid;
    }

    /**
     * Set name
     *
     * @param string $name
     *
     * @return Team
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set display name
     * @param string|null $display_name
     *
     * @return $this
     */
    public function setDisplayName(?string $display_name): self
    {
        $this->display_name = $display_name;

        return $this;
    }

    /**
     * Get display name
     * @return string|null
     */
    public function getDisplayName(): ?string
    {
        return $this->display_name;
    }

    /**
     * Get the effective name of this team
     * @return string
     */
    public function getEffectiveName(): string
    {
        return $this->getDisplayName() ?? $this->getName();
    }

    /**
     * Set categoryid
     *
     * @param integer $categoryid
     *
     * @return Team
     */
    public function setCategoryid($categoryid)
    {
        $this->categoryid = $categoryid;

        return $this;
    }

    /**
     * Get categoryid
     *
     * @return integer
     */
    public function getCategoryid()
    {
        return $this->categoryid;
    }

    /**
     * Set affilid
     *
     * @param integer $affilid
     *
     * @return Team
     */
    public function setAffilid($affilid)
    {
        $this->affilid = $affilid;

        return $this;
    }

    /**
     * Get affilid
     *
     * @return integer
     */
    public function getAffilid()
    {
        return $this->affilid;
    }

    /**
     * Set enabled
     *
     * @param boolean $enabled
     *
     * @return Team
     */
    public function setEnabled($enabled)
    {
        $this->enabled = $enabled;

        return $this;
    }

    /**
     * Get enabled
     *
     * @return boolean
     */
    public function getEnabled()
    {
        return $this->enabled;
    }

    /**
     * Set members
     *
     * @param string $members
     *
     * @return Team
     */
    public function setMembers($members)
    {
        $this->members = $members;

        return $this;
    }

    /**
     * Get members
     *
     * @return string
     */
    public function getMembers()
    {
        return $this->members;
    }

    /**
     * Set room
     *
     * @param string $room
     *
     * @return Team
     */
    public function setRoom($room)
    {
        $this->room = $room;

        return $this;
    }

    /**
     * Get room
     *
     * @return string
     */
    public function getRoom()
    {
        return $this->room;
    }

    /**
     * Set comments
     *
     * @param string $comments
     *
     * @return Team
     */
    public function setComments($comments)
    {
        $this->comments = $comments;

        return $this;
    }

    /**
     * Get comments
     *
     * @return string
     */
    public function getComments()
    {
        return $this->comments;
    }

    /**
     * Set judgingLastStarted
     *
     * @param string $judgingLastStarted
     *
     * @return Team
     */
    public function setJudgingLastStarted($judgingLastStarted)
    {
        $this->judging_last_started = $judgingLastStarted;

        return $this;
    }

webapp/src/Controller/API/TeamController.php
<?php declare(strict_types=1);

namespace App\Controller\API;

use App\Entity\Contest;
use App\Entity\Team;
use Doctrine\ORM\QueryBuilder;
use FOS\RestBundle\Controller\Annotations as Rest;
use Nelmio\ApiDocBundle\Annotation\Model;
use Swagger\Annotations as SWG;
use Symfony\Component\HttpFoundation\Request;

/**
 * @Rest\Route("/contests/{cid}/teams")
 * @SWG\Tag(name="Teams")
 * @SWG\Parameter(ref="#/parameters/cid")
 * @SWG\Response(response="404", ref="#/definitions/NotFound")
 * @SWG\Response(response="401", ref="#/definitions/Unauthorized")
 */
class TeamController extends AbstractRestController
{
    /**
     * Get all the teams for this contest
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\Response
     * @Rest\Get("")
     * @SWG\Response(
     *     response="200",
     *     description="Returns all the teams for this contest",
     *     @SWG\Schema(
     *         type="array",
     *         @SWG\Items(ref=@Model(type=Team::class))
     *     )
     * )
     * @SWG\Parameter(ref="#/parameters/idlist")
     * @SWG\Parameter(ref="#/parameters/strict")
     * @SWG\Parameter(
     *     name="category",
     *     in="query",
     *     type="string",
     *     description="Only show teams for the given category"
     * )
     * @SWG\Parameter(
     *     name="affiliation",
     *     in="query",
     *     type="string",
     *     description="Only show teams for the given affiliation / organization"
     * )
     * @SWG\Parameter(
     *     name="public",
     *     in="query",
     *     type="boolean",
     *     description="Only show visible teams, even for users with more permissions"
     * )
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function listAction(Request $request)
    {
        return parent::performListAction($request);
    }

    /**
     * Get the given team for this contest
     * @param Request $request
     * @param string $id
     * @return \Symfony\Component\HttpFoundation\Response
     * @throws \Doctrine\ORM\NonUniqueResultException
     * @Rest\Get("/{id}")
     * @SWG\Response(
     *     response="200",
     *     description="Returns the given team for this contest",
     *     @Model(type=Team::class)
     * )
     * @SWG\Parameter(ref="#/parameters/id")
     * @SWG\Parameter(ref="#/parameters/strict")
     */
    public function singleAction(Request $request, string $id)
    {
        return parent::performSingleAction($request, $id);
    }

    /**
     * @inheritdoc
     */
    protected function getQueryBuilder(Request $request): QueryBuilder
    {
        $queryBuilder = $this->em->createQueryBuilder()
            ->from(Team::class, 't')
            ->leftJoin('t.affiliation', 'ta')
            ->leftJoin('t.category', 'tc')
            ->leftJoin('t.contests', 'c')
            ->leftJoin('tc.contests', 'cc')
            ->select('t, ta');

        if ($request->query->has('category')) {
            $queryBuilder
                ->andWhere('t.categoryid = :category')
                ->setParameter(':category', $request->query->get('category'));
        }

        if ($request->query->has('affiliation')) {
            $queryBuilder
                ->andWhere('t.affilid = :affiliation')
                ->setParameter(':affiliation', $request->query->get('affiliation'));
        }

        if (!$this->dj->checkrole('api_reader') || $request->query->getBoolean('public')) {
            $queryBuilder->andWhere('tc.visible = 1');
        }

        $contest = $this->em->getRepository(Contest::class)->find($this->getContestId($request));
        if (!$contest->isOpenToAllTeams()) {
            $queryBuilder
                ->andWhere('c.cid = :cid OR cc.cid = :cid')
                ->setParameter(':cid', $contest->getCid());
        }

        return $queryBuilder;
    }

    /**
     * @inheritdoc
     * @throws \Exception
     */
    protected function getIdField(): string
    {
        return sprintf('t.%s', $this->eventLogService->externalIdFieldForEntity(Team::class) ?? 'teamid');
    }
}

webapp/src/Controller/Team/ScoreboardController.php
<?php declare(strict_types=1);

namespace App\Controller\Team;

use App\Controller\BaseController;
use App\Entity\Team;
use App\Service\ConfigurationService;
use App\Service\DOMJudgeService;
use App\Service\ScoreboardService;
use Doctrine\ORM\EntityManagerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class ScoreboardController
 *
 * @Route("/team")
 * @IsGranted("ROLE_TEAM")
 * @Security("user.getTeam() !== null", message="You do not have a team associated with your account.")
 *
 * @package App\Controller\Team
 */
class ScoreboardController extends BaseController
{
    /**
     * @var DOMJudgeService
     */
    protected $dj;

    /**
     * @var ConfigurationService
     */
    protected $config;

    /**
     * @var ScoreboardService
     */
    protected $scoreboardService;

    /**
     * @var EntityManagerInterface
     */
    protected $em;

    /**
     * ScoreboardController constructor.
     *
     * @param DOMJudgeService        $dj
     * @param ConfigurationService   $config
     * @param ScoreboardService      $scoreboardService
     * @param EntityManagerInterface $em
     */
    public function __construct(
        DOMJudgeService $dj,
        ConfigurationService $config,
        ScoreboardService $scoreboardService,
        EntityManagerInterface $em
    ) {
        $this->dj                = $dj;
        $this->config            = $config;
        $this->scoreboardService = $scoreboardService;
        $this->em                = $em;
    }

    /**
     * @Route("/scoreboard", name="team_scoreboard")
     * @param Request $request
     * @return Response
     * @throws \Exception
     */
    public function scoreboardAction(Request $request)
    {
        $user       = $this->dj->getUser();
        $response   = new Response();
        $contest    = $this->dj->getCurrentContest($user->getTeamid());
        $refreshUrl = $this->generateUrl('team_scoreboard');
        $data       = $this->scoreboardService->getScoreboardTwigData(
            $request, $response, $refreshUrl, false, false, false, $contest
        );
        $data['myTeamId'] = $user->getTeamid();

        if ($request->isXmlHttpRequest()) {
            $data['current_contest'] = $contest;
            return $this->render('partials/scoreboard.html.twig', $data, $response);
        }
        return $this->render('team/scoreboard.html.twig', $data, $response);
    }

    /**
     * @Route("/team/{teamId<\d+>}", name="team_team")
     * @param Request $request
     * @param int     $teamId
     * @return Response
     * @throws \Exception
     */
    public function teamAction(Request $request, int $teamId)
    {
        $team             = $this->em->getRepository(Team::class)->find($teamId);
        $showFlags        = (bool)$this->config->get('show_flags');
        $showAffiliations = (bool)$this->config->get('show_affiliations');
        $data             = [
            'team' => $team,
            'showFlags' => $showFlags,
            'showAffiliations' => $showAffiliations,
        ];

        if ($request->isXmlHttpRequest()) {
            return $this->render('team/team_modal.html.twig', $data);
        } else {
            return $this->render('team/team.html.twig', $data);
        }
    }
}

webapp/templates/team/partials/clarification.html.twig
<div class="card mb-3">
    <div class="card-header">
        <div class="row">
            <div class="col-sm">
                Subject:
                {% if clarification.problem %}
                    Problem {{ clarification.problem.contestProblems.first.shortname }}: {{ clarification.problem.name }}
                {% elseif clarification.category %}
                    {{ categories[clarification.category]|default('general') }}
                {% else %}
                    General issue
                {% endif %}
            </div>
            <div class="col-sm text-muted text-right">{{ clarification.submittime | printtimeHover(clarification.contest) }}</div>
        </div>
    </div>
    <div class="card-body">
        <div class="card-title">
            <div class="row">
                <div class="col-sm">
                    From:
                    {% if clarification.sender is not empty %}
                        {{ clarification.sender.effectiveName }} (t{{ clarification.sender.teamid }})
                    {% else %}
                        Jury
                    {% endif %}
                </div>
                <div class="col-sm">To:
                    {% if clarification.recipient is not empty %}
                        {{ clarification.recipient.effectiveName }} (t{{ clarification.recipient.teamid }})
                    {% elseif clarification.sender is not null %}
                        Jury
                    {% else %}
                        <strong>All</strong>
                    {% endif %}
                </div>
            </div>
        </div>

        <div class="card-text">
            <pre class="output-text bg-light p-3">{{ clarification.body|wrapUnquoted(78) }}</pre>
        </div>
    </div>
</div>

webapp/templates/team/partials/clarification_content.html.twig
<div class="container clarificationform">
    {% include 'team/partials/clarification.html.twig' with {clarification: clarification } %}
    {% for reply in clarification.replies | filter(reply => team.canViewClarification(reply)) %}
        {% include 'team/partials/clarification.html.twig' with {clarification: reply } %}
    {% endfor %}
</div>

<div class="collapse mt-3 container clarificationform" id="collapsereplyform">
    <div class="card card-body">
        {{ form_start(form) }}
        {{ form_row(form.recipient) }}
        {{ form_row(form.subject) }}
        {{ form_row(form.message) }}
        <div class="form-group">
            <button type="submit" name="submit" class="btn btn-primary">
                <i class="fas fa-envelope"></i> Send
            </button>
        </div>
        {{ form_end(form) }}
    </div>
</div>

webapp/templates/team/partials/clarification_list.html.twig
<div class="table-wrapper">
    <table class="data-table table table-striped table-hover table-sm" style="width:100%;">
        <thead class="thead-light">
        <tr>
            <th scope="col">time</th>
            <th scope="col">from</th>
            <th scope="col">to</th>
            <th scope="col">subject</th>
            <th scope="col">text</th>
        </tr>
        </thead>
        <tbody>
        {%- for clarification in clarifications %}
            {%- set link = path('team_clarification', {clarId: clarification.clarid}) %}

            <tr class="{% if team.unreadClarifications.contains(clarification) %}unseen{% endif %}">
                <td>
                    <a data-ajax-modal data-ajax-modal-after="markSeen" href="{{ link }}">
                        {{ clarification.submittime | printtime(null, clarification.contest) }}
                    </a>
                </td>
                {%- if clarification.sender is null %}
                    {%- set sender = 'Jury' %}
                    {%- if clarification.recipient is null %}
                        {%- set recipient = 'All' %}
                    {%- else %}
                        {%- set recipient = clarification.recipient.effectiveName %}
                    {%- endif %}
                {%- else %}
                    {%- set recipient = 'Jury' %}
                    {%- set sender = clarification.sender.effectiveName %}
                {%- endif %}

                <td>
                    <a data-ajax-modal data-ajax-modal-after="markSeen" href="{{ link }}" title="{{ sender }}">
                        {{ sender | truncate(30) }}
                    </a>
                </td>
                <td>
                    <a data-ajax-modal data-ajax-modal-after="markSeen" href="{{ link }}" title="{{ recipient }}">
                        {{ recipient | truncate(30) }}
                    </a>
                </td>
                <td>
                    <a data-ajax-modal data-ajax-modal-after="markSeen" href="{{ link }}">
                        {%- if clarification.problem -%}
                            problem {{ clarification.problem.contestProblems.first.shortname -}}
                        {%- elseif clarification.category -%}
                            {{- categories[clarification.category]|default('general') -}}
                        {%- else -%}
                            general
                        {%- endif -%}
                    </a>
                </td>

                <td>
                    <a data-ajax-modal data-ajax-modal-after="markSeen" href="{{ link }}">
                        {{ clarification.summary }}
                    </a>
                </td>
            </tr>
        {%- endfor %}

        </tbody>
    </table>
</div>

webapp/templates/team/partials/index_content.html.twig
{% if contest is empty %}
    <h1 id="teamwelcome" class="text-center">Welcome team <span id="teamwelcometeam">{{ team.effectiveName }}</span>!</h1>
    <h2 id="contestnotstarted" class="text-center">There's no active contest for you (yet).</h2>
{% elseif not contest.freezeData.started %}
    <h1 id="teamwelcome" class="text-center">Welcome team <span id="teamwelcometeam">{{ team.effectiveName }}</span>!</h1>
    <h2 id="contestnotstarted" class="text-center">
        Contest {{ contest | printContestStart }}
    </h2>
{% else %}

    <div id="teamscoresummary">
        {% set displayRank = not contest.freezeData.showFrozen %}
        {% include 'partials/scoreboard_table.html.twig' with {displayRank: displayRank, jury: false, public: false} %}
    </div>

    <div class="mt-4" data-flash-messages>
        {% include 'partials/messages.html.twig' %}
    </div>

    <div class="row">
        <div class="col">
            <h3 class="teamoverview">Submissions</h3>

            {% include 'team/partials/submission_list.html.twig' %}
        </div>
        <div class="col">
            <h3 class="teamoverview">Clarifications</h3>
            {% if clarifications is empty %}
                <p class="nodata">No clarifications.</p>
            {% else %}
                {% include 'team/partials/clarification_list.html.twig' with {clarifications: clarifications} %}
            {% endif %}

            <h3 class="teamoverview">Clarification Requests</h3>
            {% if clarificationRequests is empty %}
                <p class="nodata">No clarification request.</p>
            {% else %}
                {% include 'team/partials/clarification_list.html.twig' with {clarifications: clarificationRequests} %}
            {% endif %}

            <div class="m-1">
                <a href="{{ path('team_clarification_add') }}" class="btn btn-secondary btn-sm" data-ajax-modal>
                    request clarification
                </a>
            </div>
        </div>
    </div>
{% endif %}

{% if ajax is defined and ajax %}
    {% include 'partials/scoreboard_progress_bar.html.twig' with {margin: -9, contest: current_team_contest} %}
{% endif %}

webapp/templates/team/partials/submission.html.twig
{% if judging is empty or judging.submission.submittime >= current_team_contest.endtime or (verificationRequired and not judging.verified) %}
    <div class="alert alert-danger">Submission not found for this team or not judged yet.</div>
{% else %}
    <div class="container">
        {% if not judging.valid %}
            <div class="alert alert-warning">This submission is being ignored. It is not used in determining your
                score.
            </div>
        {% endif %}

        <div class="d-flex flex-row">
            <div class="p-2">
                Problem:
                <b>
                        <span class="probid">
                            {{ judging.submission.contestProblem.shortname }}</span> -
                    {{ judging.submission.contestProblem.problem.name }}
                </b>
            </div>
            <div class="p-2">
                Submitted:
                <b>{{ judging.submission.submittime | printtime(null, current_team_contest) }}</b>
            </div>
            <div class="p-2">
                Language:
                <b>{{ judging.submission.language.name }}</b>
            </div>
            <div class="p-2">
                Compilation:
                {% if judging.result == 'compiler-error' %}
                    <span class="badge badge-danger">failed</span>
                {% else %}
                    <span class="badge badge-success">successful</span>
                {% endif %}
            </div>
        </div>

        {% if judging.result != 'compiler-error' %}
            <div class="d-flex flex-row">
                <div class="p-2">
                    Run result: {{ judging.result | printResult }}
                </div>
            </div>
        {% endif %}

        {% if allowDownload %}
            <div class="d-flex flex-row">
                <div class="p-2">
                    <a class="btn btn-primary" href="{{ path('team_submission_download', {'submitId': judging.submitid}) }}">
                        <i class="fa fa-download"></i> Download submission
                    </a>
                </div>
            </div>
        {% endif %}

        {% if showCompile == 2 or (showCompile == 1 and judging.result == 'compiler-error') %}
            <hr/>
            <h4 class="text-center">Compilation output</h4>
            {% if judging.outputCompile(true) is not empty %}
                <pre class="output_text pre-scrollable">{{ judging.outputCompile(true) }}</pre>
            {% else %}
                <p class="nodata">There were no compiler errors or warnings.</p>
            {% endif %}
        {% endif %}

        {% if showSampleOutput and judging.result != 'compiler-error' %}
            <hr/>
            <h4 class="text-center">Run(s) on the provided sample data</h4>

            {% if runs is empty %}
                <p class="nodata">No sample cases available.</p>
            {% else %}
                {% for run in runs %}
                    <h5 id="run-{{ run.rank }}" class="text-center mt-4">Run {{ run.rank }}</h5>

                    {% set judgingRun = run.judgingRuns.first %}
                    {% if judgingRun == null or judgingRun.runresult == null %}
                        <p class="nodata">Run not finished yet.</p>
                    {% else %}
                        <div class="row">
                            <div class="col-md-{{ size|default(4) }}">
                                <table class="table table-sm table-striped">
                                    <tr>
                                        <th>Description</th>
                                        <td>{{ run.description(true) }}</td>
                                    </tr>
                                    <tr>
                                        <th>Runtime</th>
                                        <td>{{ judgingRun.runtime }} sec</td>
                                    </tr>
                                    <tr>
                                        <th>Result</th>
                                        <td>
                                                <span class="sol sol_{% if judgingRun.runresult != 'correct' %} in{% endif %}correct">
                                                    {{ judgingRun.runresult }}
                                                </span>
                                        </td>
                                    </tr>
                                </table>
                            </div>
                        </div>

                        <h6 class="text-center">Program output</h6>
                        {% if judgingRun.output.outputRun is not empty %}
                            <pre class="output_text">{{ judgingRun.output.outputRun }}</pre>
                        {% else %}
                            <p class="nodata">There was no program output.</p>
                        {% endif %}

                        <h6 class="text-center">Diff output</h6>
                        {% if judgingRun.output.outputDiff is not empty %}
                            <pre class="output_text">{{ judgingRun.output.outputDiff }}</pre>
                        {% else %}
                            <p class="nodata">There was no diff output.</p>
                        {% endif %}

                        <h6 class="text-center">Error output (info/debug/errors)</h6>
                        {% if judgingRun.output.outputError is not empty %}
                            <pre class="output_text">{{ judgingRun.output.outputError }}</pre>
                        {% else %}
                            <p class="nodata">There was no stderr output.</p>
                        {% endif %}
                    {% endif %}
                {% endfor %}
            {% endif %} {# not runs is empty #}
        {% endif %} {# showSampleOutput and judging.result != 'compiler-error' #}
    </div>
{% endif %} {# not (judging is empty or judging.submission.submittime >= current_team_contest.endtime or (verificationRequired and not judging.verified)) #}